import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowRight,X,Pause,Play} from '@phosphor-icons/react';
import {chapters,milestones} from './history';
import {demos} from './Demos';
import {JourneyProvider,JourneyDemo} from './Journey';
function Source({source}){return <a className="text-link" href={source[2]} target="_blank" rel="noopener noreferrer">{source[0]}<ArrowUpRight size={18}/></a>}
function Dialog({open,onClose,children,className=''}){const ref=useRef();useEffect(()=>{if(open&&!ref.current.open)ref.current.showModal();else if(!open&&ref.current.open)ref.current.close()},[open]);return <dialog ref={ref} className={className} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><button className="dialog-close circle-button" aria-label="Close panel" onClick={onClose}><X size={22}/></button>{children}</dialog>}
export function App(){
 const[active,setActive]=useState(0),[panel,setPanel]=useState(null),[detail,setDetail]=useState(null),[motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);const rail=useRef();
 function go(id){setPanel(null);setDetail(null);document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'instant',block:'start'});history.replaceState(null,'','#'+id)}
 useEffect(()=>{document.documentElement.dataset.motion=motion?'on':'off'},[motion]);
 useEffect(()=>{let frame;const sections=[...document.querySelectorAll('.chapter')];function update(){let current=0;sections.forEach((s,i)=>{const r=s.getBoundingClientRect();if(r.top<=innerHeight*.36)current=i;s.style.setProperty('--progress',Math.max(0,Math.min(1,-r.top/r.height)))});setActive(current);frame=null}function tick(){if(!frame)frame=requestAnimationFrame(update)}addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick);update();const timer=setTimeout(()=>{const id=location.hash.slice(1);if(id)document.getElementById(id)?.scrollIntoView({behavior:'instant'})},100);return()=>{removeEventListener('scroll',tick);removeEventListener('resize',tick);cancelAnimationFrame(frame);clearTimeout(timer)}},[]);
 useEffect(()=>{const item=rail.current?.children[active];if(item){const r=rail.current;if(item.offsetLeft<r.scrollLeft||item.offsetLeft+item.offsetWidth>r.scrollLeft+r.clientWidth)r.scrollTo({left:item.offsetLeft-r.clientWidth/2+item.offsetWidth/2,behavior:motion?'smooth':'instant'})}},[active,motion]);
 return <JourneyProvider><a className="skip-link" href="#html">Skip to the first interactive chapter</a><header className="site-header"><a className="wordmark" href="#web" onClick={e=>{e.preventDefault();go('web')}}>THE WEB <span className="slash">/</span><span>A LIVING HISTORY</span></a><nav aria-label="Main navigation"><button onClick={()=>setPanel('timeline')}>Timeline</button><button onClick={()=>setPanel('sources')}>Sources</button><button className="motion-toggle" aria-label={motion?'Pause ambient motion':'Enable ambient motion'} aria-pressed={!motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></nav></header>
 <main>{chapters.map((c,i)=>{const Demo=demos[c.id];return <section id={c.id} className={'chapter '+(i===0?'hero':'')} data-chapter={i} key={c.id} aria-labelledby={'title-'+c.id}><div className="chapter-sticky"><div className="chapter-copy"><p className="kicker"><span>{c.year}</span><b>·</b>{c.kind}</p>{i===0?<h1 id={'title-'+c.id}>{c.title}</h1>:<h2 id={'title-'+c.id}>{c.title}</h2>}<p className="subtitle">{c.subtitle}</p><p className="chapter-body">{c.body}</p><div className="creator"><span>{c.person}</span><p>{c.role}</p></div><div className="chapter-links"><Source source={c.sources[0]}/>{i===0&&<button className="story-link" onClick={()=>go("html")}>Follow one page through time <ArrowRight size={16}/></button>}<button className="story-link" onClick={()=>setDetail(c)}>The story & sources <ArrowRight size={16}/></button></div></div>{i===0?<div className="hero-art"><img src="/assets/connected-documents.png" alt="An artistic reconstruction of Tim Berners-Lee’s proposal, connecting floating documents with blue links." fetchPriority="high"/></div>:['html','server','css','javascript','dom','ajax'].includes(c.id)?<JourneyDemo stage={c.id} onNext={go}/>:<Demo/>}{i>0&&<div className="chapter-footnote"><p>{c.milestone}</p></div>}</div></section>})}<section className="epilogue"><p className="kicker"><span>STILL BEING WRITTEN</span></p><h2>Built on each other.<br/>Open to everyone.</h2><p>A document became a platform.<br/>The next chapter starts with what we choose to build.</p><button className="text-link" onClick={()=>setPanel('timeline')}>See the whole timeline<ArrowUpRight size={20}/></button><button className="restart" onClick={()=>go('web')}>Return to the first idea ↑</button></section></main>
 <footer className="timeline-bar"><nav ref={rail} aria-label="History chapters">{chapters.map((c,i)=><a key={c.id} href={'#'+c.id} aria-current={active===i?'step':undefined} className={active===i?'active':''} onClick={e=>{e.preventDefault();go(c.id)}}><i/><b>{c.year}</b><span>{c.nav}</span></a>)}</nav><button className="scroll-cue" onClick={()=>go(chapters[(active+1)%chapters.length].id)}>{active===12?'Back to the beginning':'Scroll to connect'}<ArrowDown size={21}/></button></footer>
 <Dialog open={!!panel} onClose={()=>setPanel(null)}><p className="kicker"><span>{panel==='timeline'?'THE COMPLETE TIMELINE':'PRIMARY SOURCES & FURTHER READING'}</span></p><h2>{panel==='timeline'?<>Every breakthrough.<br/>In its own time.</>:<>Go to the source.</>}</h2><p className="panel-intro">{panel==='timeline'?'A proposal, a working implementation and a standard can happen years apart. Each date below tells you which milestone it marks.':'Meet the people, read the original ideas, and explore the standards that made the Web possible.'}</p>{panel==='timeline'?<div className="milestones">{milestones.map((m,i)=><button key={i} onClick={()=>go(m[2])}><b>{m[0]}</b><span><strong>{m[1]}</strong><small>{m[3]}</small></span><em>{m[4]}</em><ArrowUpRight size={20}/></button>)}</div>:<div className="source-collection">{chapters.map(c=><section key={c.id}><h3><b>{c.year}</b>{c.nav}</h3><div>{c.sources.map((s,i)=><div className="source-entry" key={i}><Source source={s}/><p>{s[1]}</p></div>)}</div></section>)}<p className="demo-note">Interactive examples use modern browser APIs. Historical dates distinguish proposals, implementations and standards. Floating papers are an artistic illustration, not a document facsimile.</p></div>}</Dialog>
 <Dialog open={!!detail} onClose={()=>setDetail(null)} className="detail-dialog">{detail&&<><p className="kicker"><span>{detail.year}</span>· {detail.nav}</p><h2>A closer look.</h2><p className="detail-body">{detail.detail}</p><p className="detail-milestone">{detail.milestone}</p><div className="creator"><span>{detail.person}</span><p>{detail.role}</p></div><div className="detail-sources">{detail.sources.map((s,i)=><div className="source-entry" key={i}><Source source={s}/><p>{s[1]}</p></div>)}</div></>}</Dialog></JourneyProvider>
}
