import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowRight,X,Pause,Play} from '@phosphor-icons/react';
import {chapters,milestones} from './history';
import {demos} from './Demos';
import {JourneyProvider,JourneyDemo} from './Journey';
import {PeopleText,PeopleDirectory} from './People';
import {CernNetwork} from './CernNetwork';
import {Chronology} from './Chronology';
import {ChapterTransition,useScrollStory} from './ScrollStory';
function Source({source}){return <a className="text-link" href={source[2]} target="_blank" rel="noopener noreferrer">{source[0]}<ArrowUpRight size={18}/></a>}
function Dialog({open,onClose,children,className='',label='A closer look'}){const ref=useRef();useEffect(()=>{if(open&&!ref.current.open)ref.current.showModal();else if(!open&&ref.current.open)ref.current.close()},[open]);return <dialog ref={ref} aria-label={label} className={className} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><button className="dialog-close circle-button" aria-label="Close panel" onClick={onClose}><X size={22}/></button>{children}</dialog>}
const onward = {
 v8:['Apps can serve more people. Can the same page fit their different screens?','Change the viewport','responsive'],
 responsive:['A page fits in your pocket. What else could the browser let it do?','Explore the platform','platform'],
 platform:['The browser has become a creative space. What happens when the connection disappears?','Leave the network','offline'],
 offline:['An app can survive offline. Could an existing scientific tool run here too?','Bring a program to the Web','wasm'],
 wasm:['Portable code brings more algorithms. How do we handle lots of independent work?','Think in parallel','webgpu'],
 webgpu:['From one document to a computational canvas. What would you build on these foundations?','Explore all the milestones','timeline']
};
export function App(){
 const[active,setActive]=useState(0),[panel,setPanel]=useState(null),[detail,setDetail]=useState(null),[motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);
 function go(id){setPanel(null);setDetail(null);document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'instant',block:'start'});history.replaceState(null,'','#'+id)}
 useEffect(()=>{document.documentElement.dataset.motion=motion?'on':'off'},[motion]);
 useScrollStory(motion,setActive);
 useEffect(()=>{const id=location.hash.slice(1);if(id)requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'instant',block:'start'}))},[]);
 return <JourneyProvider><a className="skip-link" href="#html">Skip to the first interactive chapter</a><header className="site-header"><a className="wordmark" href="#web" onClick={e=>{e.preventDefault();go('web')}}>THE WEB <span className="slash">/</span><span>A LIVING HISTORY</span></a><nav aria-label="Main navigation"><button onClick={()=>setPanel('timeline')}>Timeline</button><button onClick={()=>setPanel('people')}>People</button><button onClick={()=>setPanel('sources')}>Sources</button><button className="motion-toggle" aria-label={motion?'Pause motion':'Enable motion'} aria-pressed={!motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></nav></header>
 <main>{chapters.map((c,i)=>{const Demo=demos[c.id];return <React.Fragment key={c.id}>{i>0&&<ChapterTransition from={chapters[i-1]} to={c}/>}<section id={c.id} className={'chapter '+(i===0?'hero':'')} data-chapter={i} key={c.id} aria-labelledby={'title-'+c.id}><div className="chapter-sticky"><div className="chapter-copy"><p className="kicker"><span>{c.year}</span><b>·</b>{c.kind}</p>{i===0?<h1 id={'title-'+c.id}>{c.title}</h1>:<h2 id={'title-'+c.id}>{c.title}</h2>}<p className="subtitle">{c.subtitle}</p><p className="chapter-body"><PeopleText>{c.body}</PeopleText></p><div className="creator"><span><PeopleText>{c.person}</PeopleText></span><p><PeopleText>{c.role}</PeopleText></p></div><div className="chapter-links"><button className="people-link" onClick={()=>setPanel('people')}>Meet the people · profiles & photos <ArrowUpRight size={14}/></button><Source source={c.sources[0]}/>{i===0&&<button className="story-link" onClick={()=>go("connected-ideas")}>See what a link changes <ArrowRight size={16}/></button>}<button className="story-link" onClick={()=>setDetail(c)}>The story & sources <ArrowRight size={16}/></button></div></div>{i===0?<div className="hero-art"><img src="/assets/connected-documents.png" alt="An artistic reconstruction of Tim Berners-Lee’s proposal, connecting floating documents with blue links." fetchPriority="high"/></div>:['html','server','css','javascript','dom','ajax'].includes(c.id)?<JourneyDemo stage={c.id} onNext={go}/>:<Demo/>}{onward[c.id]&&<div className="story-bridge"><p>{onward[c.id][0]}</p><button onClick={()=>onward[c.id][2]==='timeline'?setPanel('timeline'):go(onward[c.id][2])}>{onward[c.id][1]}<ArrowRight size={17}/></button></div>}{i>0&&<div className="chapter-footnote"><p>{c.milestone}</p></div>}</div>{i===0&&<CernNetwork onNext={()=>go("html")}/>}</section></React.Fragment>})}<section className="epilogue"><p className="kicker"><span>Still being written</span></p><h2>Built on each other.<br/>Open to everyone.</h2><p>A document became a platform.<br/>The next chapter starts with what we choose to build.</p><button className="text-link" onClick={()=>setPanel('timeline')}>See the whole timeline<ArrowUpRight size={20}/></button><button className="restart" onClick={()=>go('web')}>Return to the first idea ↑</button></section></main>
 <Chronology active={active} onNavigate={go}/>
 <Dialog label={panel==='people'?'People behind the Web':panel==='timeline'?'Complete timeline':'Historical sources'} open={!!panel} onClose={()=>setPanel(null)}><p className="kicker"><span>{panel==='timeline'?'THE COMPLETE TIMELINE':panel==='people'?'THE HUMAN SIDE OF THE WEB':'PRIMARY SOURCES & FURTHER READING'}</span></p><h2>{panel==='timeline'?<>Every breakthrough.<br/>In its own time.</>:panel==='people'?<>Ideas have people<br/>behind them.</>:<>Go to the source.</>}</h2><p className="panel-intro" hidden={panel==='people'}>{panel==='timeline'?'A proposal, a working implementation and a standard can happen years apart. Each date below tells you which milestone it marks.':'Meet the people, read the original ideas, and explore the standards that made the Web possible.'}</p>{panel==='people'?<PeopleDirectory/>:panel==='timeline'?<div className="milestones">{milestones.map((m,i)=><div className="milestone-entry" key={i}><button onClick={()=>go(m[2])}><b>{m[0]}</b><span><strong>{m[1]}</strong><small>{m[3]}</small></span><ArrowUpRight size={20}/></button><p><PeopleText>{m[4]}</PeopleText></p></div>)}</div>:<div className="source-collection">{chapters.map(c=><section key={c.id}><h3><b>{c.year}</b>{c.nav}</h3><div>{c.sources.map((s,i)=><div className="source-entry" key={i}><Source source={s}/><p><PeopleText>{s[1]}</PeopleText></p></div>)}</div></section>)}<p className="demo-note">Interactive examples use modern browser APIs. Historical dates distinguish proposals, implementations and standards. Floating papers are an artistic illustration, not a document facsimile.</p></div>}</Dialog>
 <Dialog open={!!detail} onClose={()=>setDetail(null)} className="detail-dialog">{detail&&<><p className="kicker"><span>{detail.year}</span>· {detail.nav}</p><h2>A closer look.</h2><p className="detail-body"><PeopleText>{detail.detail}</PeopleText></p><p className="detail-milestone">{detail.milestone}</p><div className="creator"><span><PeopleText>{detail.person}</PeopleText></span><p><PeopleText>{detail.role}</PeopleText></p></div><div className="detail-sources">{detail.sources.map((s,i)=><div className="source-entry" key={i}><Source source={s}/><p><PeopleText>{s[1]}</PeopleText></p></div>)}</div></>}</Dialog></JourneyProvider>
}
