import React,{useState,useRef,useEffect} from 'react';
import {Play,ArrowClockwise,ArrowRight} from '@phosphor-icons/react';

const wasmBytes=new Uint8Array([0,97,115,109,1,0,0,0,1,7,1,96,2,127,127,1,127,3,2,1,0,7,7,1,3,97,100,100,0,0,10,9,1,7,0,32,0,32,1,106,11]);
const noise=[0,17,-22,31,-18,8,-27,23,-14,28,-20,6,17,-24,29,-19,12,-30,16,-9,24,-25,13,-18,26,-12,7,-21,30,-17,15,-8];
export function SignalLab(){
 const [strength,setStrength]=useState(65),[filtered,setFiltered]=useState(null),[sums,setSums]=useState(null),[selected,setSelected]=useState(12),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const samples=noise.map((n,i)=>Math.round(95+Math.sin(i*.22)*43+n*strength/100));
 const x=i=>16+i*388/31,points=values=>values.map((v,i)=>`${x(i)},${190-v}`).join(' ');
 const start=Math.max(0,selected-2),end=Math.min(31,selected+2),window=samples.slice(start,end+1);
 async function smooth(){setBusy(true);try{const{instance}=await WebAssembly.instantiate(wasmBytes);const totals=samples.map((_,i)=>samples.slice(Math.max(0,i-2),Math.min(samples.length,i+3)).reduce((total,v)=>instance.exports.add(total,v),0));setSums(totals);setFiltered(totals.map((v,i)=>v/(Math.min(32,i+3)-Math.max(0,i-2))));setStatus('32 window sums calculated by WebAssembly. Explore any output below.')}catch{setStatus('WebAssembly is unavailable here. No filter was run.')}finally{setBusy(false)}}
 return <div className="demo"><div className="demo-topline"><span>The portable program</span><span>Real WebAssembly execution</span></div><p className="lesson-lead">A big signal becomes a series of small jobs. Each output averages its nearby samples. Follow one window from input to result.</p><div className="demo-window"><div className="window-bar"><span>signal-lab.wasm</span><span>32 output tasks</span></div><div className="signal-lab"><label className="range-label"><span>Noise</span><input type="range" min="0" max="100" value={strength} aria-label="Signal noise" disabled={busy} onChange={e=>{setStrength(+e.target.value);setFiltered(null);setSums(null);setStatus('')}}/><output>{strength}%</output></label><svg className="signal-chart" viewBox="0 0 420 226" role="img" aria-label={`Output ${selected+1} uses input samples ${start+1} through ${end+1}. ${filtered?'Gray is the input, blue is the smoothed signal.':'Run the module to see the blue result.'}`}>
 {[40,80,120,160].map(y=><line key={y} x1="16" y1={y} x2="404" y2={y}/>)}<rect className="signal-window" x={x(start)-5} y="18" width={x(end)-x(start)+10} height="173" rx="6"/>
 {[start,end].map((i,k)=><line className="signal-guide" key={k} x1={x(i)} x2={x(i)} y1="18" y2="197"/>)}
 <polyline className="raw" points={points(samples)}/>{filtered&&<polyline className="filtered" points={points(filtered)}/>}
 {window.map((v,i)=><circle key={i} className="signal-input" cx={x(start+i)} cy={190-v} r="3.5"/>)}
 {filtered&&<circle className="signal-output" cx={x(selected)} cy={190-filtered[selected]} r="5"/>}
 <path className="signal-bracket" d={`M${x(start)} 190 V197 H${x(end)} V190 M${x(selected)} 197 V204`}/><text x={Math.max(77,Math.min(343,x(selected)))} y="219" textAnchor="middle">{window.length} inputs → output {selected+1}</text>
 </svg><p className="signal-key">Gray: original · Blue: smoothed · Shaded: selected window</p>
 <label className="range-label task-selector"><span>Explore output</span><input type="range" min="1" max="32" value={selected+1} aria-label="Explore signal output" onChange={e=>setSelected(+e.target.value-1)}/><output>{selected+1} / 32</output></label>
 <div className="window-recipe"><div><small>Read {window.length} samples</small><span>{window.join(' + ')}</span></div><ArrowRight size={16}/><div><small>Sum in Wasm</small><strong>{sums?sums[selected]:'Σ'}</strong></div><ArrowRight size={16}/><div><small>Divide by {window.length} in JS</small><strong>{filtered?filtered[selected].toFixed(1):'mean'}</strong></div></div>
 <button className="pill-primary" onClick={smooth} disabled={busy}><Play size={16}/>{busy?'Running…':'Smooth with WebAssembly'}</button><p className="result-message" role="status">{status||'Move the window, change the noise, then run the module.'}</p></div></div><p className="lab-discovery"><b>The breakthrough:</b> a web interface can call portable compiled code. Here, overlapping input windows produce 32 independent outputs; this demo calculates them in sequence.</p><details className="technical-details"><summary>What actually runs?</summary><p>A real 41-byte Wasm module exports integer addition. JavaScript calls it to sum each five-sample window, divides by its length, and draws the chart. Windows at the ends contain fewer samples. This educational module is pre-encoded, not compiled from C or Rust at runtime. It demonstrates the boundary between JavaScript and Wasm, not a speed advantage.</p><pre className="code-block"><code>{'const { instance } = await WebAssembly.instantiate(bytes);\nconst sum = values.reduce(instance.exports.add, 0);\nconst average = sum / values.length;'}</code></pre></details></div>
}
const modes=[['sequential','One at a time'],['parallel','Eight together'],['gpu','On your GPU']];
const formatTime=ms=>ms===null?'—':ms<1000?`${ms.toFixed(1)} ms`:`${(ms/1000).toFixed(2)} s`;
export function ParallelLab(){
 const [mode,setMode]=useState('parallel'),[done,setDone]=useState(0),[running,setRunning]=useState(false),[result,setResult]=useState(''),[elapsed,setElapsed]=useState(null),[records,setRecords]=useState({}),[gpuValues,setGpuValues]=useState(null);
 const timer=useRef(null),clock=useRef(null),generation=useRef(0);
 useEffect(()=>()=>{clearInterval(timer.current);clearInterval(clock.current);generation.current++},[]);
 function stop(){clearInterval(timer.current);clearInterval(clock.current);generation.current++;setRunning(false)}
 function reset(next=mode){stop();setMode(next);setDone(0);setElapsed(null);setResult('');setGpuValues(null)}
 function run(){
  stop();setDone(0);setGpuValues(null);setResult('');setRunning(true);setElapsed(0);const started=performance.now(),token=generation.current;
  const guided=mode!=='gpu'&&document.documentElement.dataset.storyPlayback==='playing';let pausedTime=0,lastMeasured=started;
  const measure=()=>{const now=performance.now();if(guided&&document.documentElement.dataset.storyPlayback==='paused')pausedTime+=now-lastMeasured;lastMeasured=now;return now-started-pausedTime};
  clock.current=setInterval(()=>setElapsed(measure()),40);
  function finish(ms,message){if(token!==generation.current)return;clearInterval(timer.current);clearInterval(clock.current);setElapsed(ms);setRunning(false);setResult(message);setRecords(previous=>({...previous,[mode]:ms}))}
  if(mode==='gpu'){compute(token,started,finish);return}
  let completed=0;timer.current=setInterval(()=>{if(guided&&document.documentElement.dataset.storyPlayback==='paused')return;completed=Math.min(64,completed+(mode==='parallel'?8:1));setDone(completed);if(completed===64)finish(measure(),'64 squares complete. This timer includes the deliberate animation delay.')},85);
 }
 async function compute(token,started,finish){let device;try{
  if(!navigator.gpu)throw Error('unsupported');setResult('Preparing your GPU and compute pipeline…');
  const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('unsupported');device=await adapter.requestDevice();
  if(token!==generation.current)return;
  const values=new Float32Array(Array.from({length:64},(_,i)=>i+1));const storage=device.createBuffer({size:256,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC});const readback=device.createBuffer({size:256,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
  device.queue.writeBuffer(storage,0,values);const module=device.createShaderModule({code:'@group(0) @binding(0) var<storage,read_write> values: array<f32>; @compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id: vec3<u32>) { values[id.x] = values[id.x] * values[id.x]; }'});
  const pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});if(token!==generation.current)return;
  const bindGroup=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:storage}}]});const encoder=device.createCommandEncoder();const pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bindGroup);pass.dispatchWorkgroups(1);pass.end();encoder.copyBufferToBuffer(storage,0,readback,0,256);setResult('Running 64 invocations and reading the results…');device.queue.submit([encoder.finish()]);await readback.mapAsync(GPUMapMode.READ);
  const actual=Array.from(new Float32Array(readback.getMappedRange().slice(0)));readback.unmap();storage.destroy();readback.destroy();if(actual.some((v,i)=>v!==(i+1)**2))throw Error('verification');
  if(token!==generation.current)return;setGpuValues(actual);setDone(64);finish(performance.now()-started,'Verified: all 64 values were squared on your GPU. The grid shows the returned values.');
 }catch{if(token===generation.current){clearInterval(clock.current);setRunning(false);setElapsed(null);setResult('WebGPU could not run in this browser or device. No GPU result or timing is shown. Try either illustration.')}}finally{device?.destroy()}}
 return <div className="demo"><div className="demo-topline"><span>The parallel idea</span><span>Same job, different scheduling</span></div><p className="lesson-lead">64 numbers, one formula: square each value. Watch one job at a time, eight together, then try the same work on your GPU.</p><div className="demo-tabs compute-tabs" role="group" aria-label="Work scheduling">{modes.map(([key,label])=><button key={key} className={mode===key?'selected':''} aria-pressed={mode===key} onClick={()=>reset(key)}>{label}<small>{key==='gpu'?'Real compute':'Illustration'}</small></button>)}</div>
 <div className="gpu-surface parallel-lab"><div className="compute-timer"><span>{mode==='gpu'?'End-to-end compute time':'Illustration elapsed time'}</span><output>{formatTime(elapsed)}</output></div><div className="compute-grid" aria-label={`${done} of 64 ${mode==='gpu'?'GPU':'illustrated'} tasks complete`}>{Array.from({length:64},(_,i)=><span key={i} className={'compute-cell '+(i<done?'done':'')}>{i<done?(gpuValues?gpuValues[i]:(i+1)**2):i+1}</span>)}</div><div className="compute-legend"><span>Input → input × input</span><output aria-live="polite">{done} of 64 tasks</output></div><div className="demo-actions"><button className="pill-primary" onClick={run} disabled={running}><Play size={16}/>{running?'Processing…':mode==='gpu'?'Run on your GPU':'Run the illustration'}</button><button className="small-button" aria-label="Reset work illustration" onClick={()=>reset()}><ArrowClockwise size={16}/></button></div><p className="result-message" role="status">{result||(mode==='gpu'?'Real WebGPU execution, if supported by your browser and device.':'A deliberately slowed illustration: one or eight cells every 85 ms.')}</p></div>
 <div className="compute-records" aria-label="Most recent run times">{modes.map(([key,label])=><div key={key}><span>{label}</span><strong>{formatTime(records[key]??null)}</strong><small>{key==='gpu'?'Setup + compute + readback':'Includes animation delay'}</small></div>)}</div><p className="demo-note">Illustration timers pause with the guided story. These timers measure different things, so they are not a CPU/GPU benchmark. The GPU timer includes initialization and data transfer; 64 values are too few to demonstrate a meaningful speed advantage.</p><p className="lab-discovery"><b>The breakthrough:</b> the browser can dispatch general computation to a GPU. Independent work can be distributed across many invocations; transfer costs and dependencies still matter.</p></div>
}
