import React,{useState,useRef,useEffect} from 'react';
import {Play,ArrowClockwise,ArrowRight} from '@phosphor-icons/react';

const wasmBytes=new Uint8Array([0,97,115,109,1,0,0,0,1,7,1,96,2,127,127,1,127,3,2,1,0,7,7,1,3,97,100,100,0,0,10,9,1,7,0,32,0,32,1,106,11]);
const noise=[0,17,-22,31,-18,8,-27,23,-14,28,-20,6,17,-24,29,-19,12,-30,16,-9,24,-25,13,-18,26,-12,7,-21,30,-17,15,-8];
export function SignalLab(){
 const [strength,setStrength]=useState(65),[filtered,setFiltered]=useState(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const samples=noise.map((n,i)=>Math.round(95+Math.sin(i*.22)*43+n*strength/100));
 const points=values=>values.map((v,i)=>`${16+i*388/31},${190-v}`).join(' ');
 async function smooth(){setBusy(true);try{const{instance}=await WebAssembly.instantiate(wasmBytes);const output=samples.map((_,i)=>{const local=samples.slice(Math.max(0,i-2),Math.min(samples.length,i+3));const sum=local.reduce((total,v)=>instance.exports.add(total,v),0);return sum/local.length});setFiltered(output);setStatus('Signal smoothed. Every window sum was calculated by the WebAssembly module.')}catch{setStatus('WebAssembly is unavailable here. No filter was run.')}finally{setBusy(false)}}
 return <div className="demo"><div className="demo-topline"><span>The portable program</span><span>Real WebAssembly execution</span></div><p className="lesson-lead">Imagine bringing a scientific tool into a browser. Start small: pass a noisy signal to a portable module, then see the result return to your page.</p><div className="demo-window"><div className="window-bar"><span>signal-lab.wasm</span><span>32 samples</span></div><div className="signal-lab"><label className="range-label"><span>Noise</span><input type="range" min="0" max="100" value={strength} aria-label="Signal noise" onChange={e=>{setStrength(+e.target.value);setFiltered(null);setStatus('')}}/><output>{strength}%</output></label><svg className="signal-chart" viewBox="0 0 420 210" role="img" aria-label={filtered?'Noisy signal in gray with its smoothed result in blue':'A noisy signal, ready to smooth'}>{[40,80,120,160].map(y=><line key={y} x1="16" y1={y} x2="404" y2={y}/>)}<polyline className="raw" points={points(samples)}/>{filtered&&<polyline className="filtered" points={points(filtered)}/>}</svg><p className="signal-key">Gray: original samples · Blue: moving average</p><button className="pill-primary" onClick={smooth} disabled={busy}><Play size={16}/>{busy?'Running…':'Smooth with WebAssembly'}</button><p className="result-message" role="status">{status||'Change the noise, then run the module.'}</p></div></div><p className="lab-discovery"><b>The breakthrough:</b> a web interface can call portable compiled code. Scientific tools, games and editors can bring existing algorithms to the browser.</p><details className="technical-details"><summary>What actually runs?</summary><p>A real 41-byte Wasm module exports integer addition. JavaScript calls that function to sum each five-sample window, divides by its length, and draws the chart. This small educational module is pre-encoded, not compiled from C or Rust at runtime. It demonstrates the boundary between JavaScript and Wasm, not a speed advantage.</p><pre className="code-block"><code>{'const { instance } = await WebAssembly.instantiate(bytes);\nconst sum = values.reduce(instance.exports.add, 0);\nconst average = sum / values.length;'}</code></pre></details></div>
}
export function ParallelLab(){
 const [mode,setMode]=useState('parallel'),[done,setDone]=useState(0),[running,setRunning]=useState(false),[result,setResult]=useState(''),[busy,setBusy]=useState(false);const timer=useRef(null);
 useEffect(()=>()=>clearInterval(timer.current),[]);
 function stop(){clearInterval(timer.current);setRunning(false)}
 function reset(next=mode){stop();setMode(next);setDone(0)}
 function run(){stop();setDone(0);setRunning(true);let completed=0;timer.current=setInterval(()=>{completed=Math.min(64,completed+(mode==='parallel'?8:1));setDone(completed);if(completed===64){clearInterval(timer.current);setRunning(false)}},85)}
 async function compute(){setBusy(true);setResult('');let device;try{if(!navigator.gpu)throw Error();const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error();device=await adapter.requestDevice();const values=new Float32Array(Array.from({length:64},(_,i)=>i+1));const storage=device.createBuffer({size:256,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC});const readback=device.createBuffer({size:256,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});device.queue.writeBuffer(storage,0,values);const module=device.createShaderModule({code:'@group(0) @binding(0) var<storage,read_write> values: array<f32>; @compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id: vec3<u32>) { values[id.x] = values[id.x] * values[id.x]; }'});const pipeline=device.createComputePipeline({layout:'auto',compute:{module,entryPoint:'main'}});const bindGroup=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:storage}}]});const encoder=device.createCommandEncoder();const pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bindGroup);pass.dispatchWorkgroups(1);pass.end();encoder.copyBufferToBuffer(storage,0,readback,0,256);device.queue.submit([encoder.finish()]);await readback.mapAsync(GPUMapMode.READ);const actual=Array.from(new Float32Array(readback.getMappedRange().slice(0)));readback.unmap();storage.destroy();readback.destroy();if(actual.some((v,i)=>v!==(i+1)**2))throw Error();setResult(`Verified on your GPU: 64 values squared. First eight: ${actual.slice(0,8).join(', ')}. Last value: ${actual[63]}.`)}catch{setResult('WebGPU could not run in this browser or device. The illustration is still available; no GPU result is being shown.')}finally{device?.destroy();setBusy(false)}}
 return <div className="demo"><div className="demo-topline"><span>The parallel idea</span><span>Same job, different scheduling</span></div><p className="lesson-lead">A simulation may apply the same formula to thousands of cells. If those cells do not depend on each other, why process them one by one?</p><div className="demo-tabs" role="group" aria-label="Work scheduling"><button className={mode==='sequential'?'selected':''} aria-pressed={mode==='sequential'} onClick={()=>reset('sequential')}>One at a time</button><button className={mode==='parallel'?'selected':''} aria-pressed={mode==='parallel'} onClick={()=>reset('parallel')}>Eight together</button></div><div className="gpu-surface parallel-lab"><div className="compute-grid" aria-label={`${done} of 64 illustrated tasks complete`}>{Array.from({length:64},(_,i)=><span key={i} className={'compute-cell '+(i<done?'done':'')}>{i<done?(i+1)**2:i+1}</span>)}</div><div className="compute-legend"><span>Input → input × input</span><output aria-live="polite">{done} of 64 tasks</output></div><div className="demo-actions"><button className="pill-primary" onClick={run} disabled={running}><Play size={16}/>{running?'Processing…':'Run the illustration'}</button><button className="small-button" aria-label="Reset work illustration" onClick={()=>reset()}><ArrowClockwise size={16}/></button></div></div><p className="demo-note">Deliberately slowed illustration: one or eight cells per tick. This is not GPU execution, a CPU/GPU benchmark, or a promise of an eightfold speed-up.</p><p className="lab-discovery"><b>The breakthrough:</b> the browser can dispatch general computation to a GPU. Independent work can be distributed across many invocations; transfer costs and dependencies still matter.</p><div className="gpu-real"><button className="text-link" disabled={busy} onClick={compute}>{busy?'Requesting a GPU…':'Try the same job on your GPU'}<ArrowRight size={16}/></button><p className="result-message" role="status">{result||'An optional, real compute shader. Requires WebGPU support.'}</p></div></div>
}
