import React, {useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowClockwise,Plus,Minus,Check,Code,PaperPlaneTilt,Play,Pause,WifiHigh,WifiSlash,CursorClick} from '@phosphor-icons/react';

const CodeBlock=({children})=><pre className="code-block"><code>{children}</code></pre>;
const Note=({children})=><p className="demo-note">{children}</p>;
function Tabs({items,value,onChange,label}) { return <div className="demo-tabs" role="group" aria-label={label}>{items.map(([id,text])=><button key={id} className={value===id?'selected':''} aria-pressed={value===id} onClick={()=>onChange(id)}>{text}</button>)}</div>; }
function Window({name,children,className=''}){return <div className={'demo-window '+className}><div className="window-bar"><span>{name}</span><Code size={17}/></div>{children}</div>}

export function HtmlDemo(){
 const [part,setPart]=useState('heading'),[title,setTitle]=useState('A connected world'),[followed,setFollowed]=useState(false);
 const code={heading:`<h1>${title || 'A connected world'}</h1>`,paragraph:'<p>Ideas belong together.</p>',link:'<a href="/another-idea">Follow an idea</a>'};
 return <div className="demo html-demo"><div className="demo-topline"><span>01 / THE STRUCTURE</span><span>Try editing the heading</span></div><Window name="a-small-piece-of-the-web.html"><Tabs label="HTML elements" items={[["heading","Heading"],["paragraph","Paragraph"],["link","Link"]]} value={part} onChange={setPart}/><div className="html-output"><span className="small-label">BROWSER VIEW</span><h3 className={part==='heading'?'highlight-element':''}>{followed?'You followed a link.':title||'A connected world'}</h3><p className={part==='paragraph'?'highlight-element':''}>{followed?'Another document. The same open Web.':'Ideas belong together.'}</p><button className={'text-link classic-link '+(part==='link'?'highlight-element':'')} onClick={()=>{setPart('link');setFollowed(!followed)}}>{followed?'Return to the first page':'Follow an idea'}<ArrowRight size={18}/></button></div><CodeBlock>{code[part]}</CodeBlock></Window><label className="input-row"><span>Your heading</span><input value={title} maxLength={40} onChange={e=>{setTitle(e.target.value);setFollowed(false);setPart('heading')}}/></label><div className="three-definitions"><span><b>HTML</b>Structure</span><span><b>URL</b>Address</span><span><b>HTTP</b>Transfer</span></div><Note>A small, modern example of the original idea. The link navigates within this demonstration.</Note></div>
}

export function CookieDemo(){
 const [count,setCount]=useState(0),[remember,setRemember]=useState(true),[visits,setVisits]=useState(1),[message,setMessage]=useState('Add something to your cart.');
 function revisit(){setVisits(v=>v+1);if(!remember){setCount(0);setMessage('A new visitor. The server cannot match the old cart.')}else setMessage('Welcome back. The session ID matches your saved cart.')}
 return <div className="demo"><div className="demo-topline"><span>02 / STATE</span><span>Local simulation</span></div><Window name="the-first-little-shop.example"><div className="shop-header"><span className="small-label">THE CURIOSITY SHOP</span><span>Visit {visits}</span></div><div className="shop-item"><div><h3>A very good idea.</h3><p>One item. A small experiment.</p></div><button className="circle-button" aria-label="Add an idea to cart" onClick={()=>{setCount(v=>v+1);setMessage('The server updates your cart.')}}><Plus size={22}/></button></div><div className="cart-count"><span>YOUR CART</span><strong>{count.toString().padStart(2,'0')}</strong><span>{count===1?'idea':'ideas'}</span></div><div className="shop-actions"><label className="check-control"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Keep a session cookie</label><button className="small-button" onClick={revisit}><ArrowClockwise size={16}/>Return to the shop</button></div></Window><div className="state-pair"><div><span>IN THE BROWSER</span><code>{remember?'session=visitor_42':'No identifier'}</code></div><ArrowRight size={24}/><div><span>ON THE SERVER</span><code>cart: {count} {count===1?'idea':'ideas'}</code></div></div><p className="result-message" role="status">{message}</p><Note>Conceptual simulation: no real cookie, account, payment or server request is created.</Note></div>
}

export function CssDemo(){
 const [theme,setTheme]=useState('plain');
 const rules={plain:'/* No presentation rules. Just HTML. */',editorial:'h1 { font-size: 3rem; }\narticle { padding: 2.5rem; }\na { color: #0014dc; }',night:'article { background: #13214b; }\nh1 { color: #ffffff; }\na { color: #a9baff; }'};
 return <div className="demo"><div className="demo-topline"><span>03 / THE PRESENTATION</span><span>Change the CSS. Keep the HTML.</span></div><Tabs label="CSS styles" items={[["plain","No CSS"],["editorial","Editorial"],["night","After dark"]]} value={theme} onChange={setTheme}/><Window name="same-content.html"><article className={'css-specimen '+theme}><span className="specimen-kicker">THE DAILY WEB / ISSUE 001</span><h3>A connected<br/>world.</h3><p>One document. Many possible expressions.<br/>The words stay exactly the same.</p><span className="specimen-link">An idea worth sharing.</span></article><CodeBlock>{rules[theme]}</CodeBlock></Window><Note>Switch between styles. Content and structure stay unchanged; presentation transforms.</Note></div>
}

export function JsDemo(){
 const [count,setCount]=useState(0),[enabled,setEnabled]=useState(true);
 return <div className="demo"><div className="demo-topline"><span>04 / THE BEHAVIOR</span><span>Click. Run a function. See a change.</span></div><Window name="a-page-that-responds.html"><div className="js-stage"><span className="small-label">IDEAS SHARED</span><output className="big-number" aria-live="polite">{count.toString().padStart(2,'0')}</output><div className="counter-controls"><button className="circle-button" aria-label="Remove an idea" disabled={!enabled||count===0} onClick={()=>setCount(v=>v-1)}><Minus size={24}/></button><button className="pill-primary" disabled={!enabled} onClick={()=>setCount(v=>v+1)}><Plus size={20}/>Share an idea</button></div><span className="counter-feedback">{!enabled?'Behavior switched off in this demo.':count?'A click changed the value. No new page.':'Waiting for your first click.'}</span></div><CodeBlock>{`let ideas = ${count};\nbutton.addEventListener("click", () => {\n  counter.textContent = ++ideas;\n});`}</CodeBlock></Window><label className="check-control bottom-control"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable the JavaScript behavior</label><Note>The switch simulates removing the event handler from this example, not disabling JavaScript in your browser.</Note></div>
}

export function DomDemo(){
 const [selected,setSelected]=useState('h1'),[changed,setChanged]=useState({}),[extra,setExtra]=useState(false);
 return <div className="demo"><div className="demo-topline"><span>05 / THE LIVE DOCUMENT</span><span>Select a node. Change its content.</span></div><Window name="document"><div className="dom-layout"><div className="dom-tree"><span className="small-label">DOCUMENT TREE</span><span className="tree-root">document</span><div className="tree-level"><span>html</span><div className="tree-level"><span>body</span><div className="tree-level">{['h1','p','a',...(extra?['p.new']:[])].map(n=><button aria-pressed={selected===n} className={selected===n?'active-node':''} onClick={()=>setSelected(n)} key={n}>{'<'+n+'>'}</button>)}</div></div></div></div><article className="dom-output"><h3 className={selected==='h1'?'highlight-element':''}>{changed.h1?'Hello, living Web.':'A connected world.'}</h3><p className={selected==='p'?'highlight-element':''}>{changed.p?'This text changed in place.':'Ideas belong together.'}</p><a href="#html" className={selected==='a'?'highlight-element':''}>{changed.a?'A different label':'Follow an idea'}</a>{extra&&<p className={selected==='p.new'?'highlight-element':''}>{changed['p.new']?'This new node changed too.':'A new node just appeared.'}</p>}</article></div><CodeBlock>{extra?'document.body.append(newParagraph);':`document.querySelector("${selected}").textContent\n  = "${selected==='h1'?'Hello, living Web.':selected==='p'?'This text changed in place.':'A different label'}";`}</CodeBlock></Window><div className="demo-actions"><button className="small-button" onClick={()=>setChanged(v=>({...v,[selected]:!v[selected]}))}>Change selected text</button><button className="small-button" onClick={()=>{setExtra(v=>!v);setSelected(extra?'h1':'p.new')}}>{extra?'Remove new node':'Add a paragraph'}</button></div><Note>Click the tree to locate the matching element. The tree and visible document describe the same structure.</Note></div>
}

const editions=[['A new idea arrived.','A better way to share.','The conversation continues.'],['The map just moved.','Only this part changed.','Everything else stayed.'],['Another message, instantly.','Small updates. Big difference.','The page never left.']];
export function AjaxDemo(){
 const [mode,setMode]=useState('ajax'),[edition,setEdition]=useState(0),[loading,setLoading]=useState(false),[draft,setDraft]=useState('Keep my place, please.');const timer=useRef();
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 function update(){if(loading)return;setLoading(true);if(mode==='reload')setDraft('');timer.current=setTimeout(()=>{setEdition(v=>(v+1)%editions.length);setLoading(false)},900)}
 return <div className="demo"><div className="demo-topline"><span>06 / THE UPDATE</span><span>Compare what gets replaced</span></div><Tabs label="Page update mode" items={[["reload","Full-page navigation"],["ajax","AJAX update"]]} value={mode} onChange={setMode}/><Window name="the-live-inbox.example"><div className="ajax-shell"><div className="inbox-header"><h3>Your little inbox.</h3><button className="circle-button" disabled={loading} aria-label="Get new messages" onClick={update}><ArrowClockwise size={20} className={loading?'spinning':''}/></button></div><label className="draft-label">An unfinished thought<input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a thought to keep…"/></label><div className={'inbox-messages '+(loading?'updating':'')} aria-live="polite">{editions[edition].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></div>)}{loading&&mode==='ajax'&&<span className="update-label">Updating messages only…</span>}</div>{loading&&mode==='reload'&&<div className="reload-overlay"><ArrowClockwise size={28} className="spinning"/><span>Loading a whole new page…</span></div>}</div></Window><button className="text-link demo-cta" onClick={update} disabled={loading}>Fetch the next edition<ArrowRight size={19}/></button><Note>Local simulation. Full-page navigation discards this example’s unsaved input; an AJAX update preserves it. Browser form-restoration behavior can vary.</Note></div>
}

export function RuntimeDemo(){
 const [mode,setMode]=useState('blocking'),[running,setRunning]=useState(false),[step,setStep]=useState(0);const timers=useRef([]);
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 function run(){timers.current.forEach(clearTimeout);setStep(1);setRunning(true);const delays=mode==='blocking'?[650,1300,1950,2600]:[550,800,1300,1700];delays.forEach((d,i)=>timers.current.push(setTimeout(()=>{setStep(i+2);if(i===3)setRunning(false)},d)))}
 const states=mode==='blocking'?['Waiting for a file…','Still waiting…','File ready. Now answer the other request.','All work finished.']:['File request started.','Answer another request while waiting.','File is ready: run its callback.','All work finished.'];
 return <div className="demo"><div className="demo-topline"><span>07 / THE RUNTIME</span><span>A conceptual event-loop illustration</span></div><Tabs label="Runtime behavior" items={[["blocking","Wait, then work"],["async","Asynchronous I/O"]]} value={mode} onChange={v=>{timers.current.forEach(clearTimeout);setMode(v);setStep(0);setRunning(false)}}/><div className="runtime-stage"><div className="runtime-lane"><span className="small-label">READ A FILE</span><div className="task-track"><span style={{width:step?`${Math.min(100,(step/(mode==='blocking'?3:4))*100)}%`:0}}/></div></div><div className="runtime-lane"><span className="small-label">ANSWER ANOTHER REQUEST</span><div className="task-track"><span style={{width:step>=(mode==='blocking'?4:2)?'100%':0}}/></div></div><div className="runtime-status" role="status">{step?states[Math.min(3,step-1)]:'Two requests. How should we handle the wait?'}</div><button className="pill-primary" onClick={run} disabled={running}><Play size={18}/>{running?'Running the illustration…':'Run the sequence'}</button></div><CodeBlock>{'readFile("ideas.txt", (error, data) => {\n  // This callback runs when I/O completes.\n});\n// Other work can continue while I/O is pending.'}</CodeBlock><Note>Illustrative timing only. Non-blocking I/O does not mean all JavaScript executes in parallel.</Note></div>
}

export function ResponsiveDemo(){
 const [width,setWidth]=useState(640);
 const src=`<!doctype html><html><head><style>*{box-sizing:border-box}body{margin:0;padding:28px;color:#202126;font:16px Arial,sans-serif;background:white}small{font-size:11px;letter-spacing:2px;color:#0014dc}h1{font-size:44px;letter-spacing:-2px;line-height:1.02;font-weight:400;margin:28px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;border-top:1px solid #ddd;padding-top:20px}.grid b{font-size:14px;color:#0014dc}.grid p{font-size:15px;line-height:1.5} @media(max-width:480px){h1{font-size:32px}.grid{grid-template-columns:1fr;gap:4px}.grid p{margin:4px 0 12px}body{padding:20px}}</style></head><body><small>THE DAILY WEB</small><h1>One world.<br>Many windows.</h1><div class="grid"><div><b>Read</b><p>An idea, wherever you are.</p></div><div><b>Share</b><p>A conversation that travels.</p></div><div><b>Create</b><p>The same Web, in your hands.</p></div></div></body></html>`;
 return <div className="demo"><div className="demo-topline"><span>08 / THE ADAPTIVE LAYOUT</span><output>{width} CSS px</output></div><label className="range-label"><span>Phone</span><input aria-label="Demo viewport width" type="range" min="280" max="640" step="10" value={width} onChange={e=>setWidth(+e.target.value)}/><span>Desktop</span></label><div className="responsive-stage"><iframe title="A responsive document" sandbox="" srcDoc={src} style={{width}}/></div><CodeBlock>{'@media (max-width: 480px) {\n  .grid { grid-template-columns: 1fr; }\n}'}</CodeBlock><Note>This is a real CSS media query inside a resizable frame. Drag to cross the 480 px breakpoint.</Note></div>
}

export function WaveField({parallel=true,playing=true,density=34,label='Interactive surface'}){
 const ref=useRef(null);const pointer=useRef({x:0,y:0});
 useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame,t=0,visible=true,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)};const ro=new ResizeObserver(resize);ro.observe(c);resize();const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting});io.observe(c);
 function draw(now){frame=requestAnimationFrame(draw);if(!visible||now-last<30)return;last=now;if(playing&&!reduced&&document.documentElement.dataset.motion!=="off")t+=0.028;const {width:w,height:h}=c.getBoundingClientRect();ctx.clearRect(0,0,w,h);const n=density,ang=.52+pointer.current.x*.3;for(let z=0;z<n;z++)for(let x=0;x<n;x++){let px=(x/(n-1)-.5)*2,pz=(z/(n-1)-.5)*2;const phase=parallel?t:Math.floor((t*5)%(n))*0.12+(z<Math.floor(t*5)%n?t:0);let py=Math.sin(px*3+phase)*Math.cos(pz*2.4+phase*.7)*.25;let rx=px*Math.cos(ang)-pz*Math.sin(ang),rz=px*Math.sin(ang)+pz*Math.cos(ang);let sx=w*.5+rx*w*.28,sy=h*.54+rz*h*.18-py*h*.50+pointer.current.y*rx*18;ctx.fillStyle=`rgba(0,20,220,${.24+((z+n)/(2*n))*.64})`;ctx.beginPath();ctx.arc(sx,sy,1.3+(rz+2)*.25,0,Math.PI*2);ctx.fill();}}frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect()};},[parallel,playing,density]);
 return <canvas ref={ref} className="wave-canvas" aria-label={label} role="img" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5}}} onPointerLeave={()=>pointer.current={x:0,y:0}}/>
}

function GraphicsDemo(){const [playing,setPlaying]=useState(false);return <><WaveField playing={playing} label="An animated mathematical surface projected from three dimensions"/><div className="demo-actions"><button className="small-button" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Pause the surface':'Animate the surface'}</button><span className="muted">Move your pointer to change the view</span></div><Note>A 3D projection illustrated with Canvas 2D so it remains usable without GPU support. WebGL enables GPU-rendered scenes.</Note></>}
function RealtimeDemo(){const [message,setMessage]=useState('Hello from the other side.'),[sent,setSent]=useState(''),[pending,setPending]=useState(false);const timer=useRef();useEffect(()=>()=>clearTimeout(timer.current),[]);function send(e){e.preventDefault();if(!message.trim())return;setPending(true);timer.current=setTimeout(()=>{setSent(message);setPending(false)},350)}return <><div className="chat-pair"><div><span className="small-label">BROWSER A</span><form onSubmit={send}><label className="sr-only" htmlFor="message">Message to send</label><input id="message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={80}/><button className="circle-button" disabled={pending||!message.trim()} aria-label="Send a demo message"><PaperPlaneTilt size={21}/></button></form></div><ArrowRight size={24}/><div><span className="small-label">BROWSER B</span><p aria-live="polite">{pending?'Delivering…':sent||'Waiting for a message…'}</p></div></div><Note>Local message-delivery simulation. A real WebSocket application uses a persistent connection and a server between clients.</Note></>}
function AudioDemo(){const [playing,setPlaying]=useState(false),[error,setError]=useState('');const context=useRef(),timer=useRef();useEffect(()=>()=>{clearTimeout(timer.current);context.current?.close()},[]);async function play(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error();const a=new C();context.current=a;await a.resume();const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(440,a.currentTime);o.frequency.exponentialRampToValueAtTime(660,a.currentTime+.35);g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.7);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.7);setPlaying(true);timer.current=setTimeout(()=>{setPlaying(false);a.close()},800)}catch{setError('Audio is unavailable in this browser.')}}return <div className="audio-demo"><span className="small-label">A SOUND, MADE IN YOUR BROWSER</span><button className="audio-play" aria-label="Play a short synthesized tone" disabled={playing} onClick={play}>{playing?<Pause size={34}/>:<Play size={34}/>}</button><p>{error||'A tiny note. No plug-in.'}</p><Note>This uses the Web Audio API, a related web-platform API rather than the HTML audio element itself. Plays only when you press the button.</Note></div>}
export function PlatformDemo(){const[tab,setTab]=useState('graphics');return <div className="demo"><div className="demo-topline"><span>09 / THE OPEN WEB PLATFORM</span><span>Explore a capability</span></div><Tabs label="Browser platform capabilities" items={[["graphics","Graphics"],["realtime","Real time"],["audio","Audio"]]} value={tab} onChange={setTab}/><Window name={tab==='graphics'?'a-canvas-for-3d':tab==='realtime'?'an-open-connection':'native-browser-audio'}><div className="platform-inner">{tab==='graphics'?<GraphicsDemo/>:tab==='realtime'?<RealtimeDemo/>:<AudioDemo/>}</div></Window></div>}

export function OfflineDemo(){const[cached,setCached]=useState(false),[online,setOnline]=useState(true),[loaded,setLoaded]=useState(false);return <div className="demo"><div className="demo-topline"><span>10 / THE RESILIENT APP</span><span>Conceptual cache simulation</span></div><Window name="the-offline-reading-room"><div className="offline-inner"><div className="connection-state">{online?<WifiHigh size={22}/>:<WifiSlash size={22}/>}<span>{online?'Connected':'Offline'}</span><button className="text-link" onClick={()=>{setOnline(v=>!v);setLoaded(false)}}>Go {online?'offline':'online'}</button></div><article className={'offline-paper '+(!online&&!cached?'unavailable':'')}><span className="small-label">SAVED FOR A QUIETER MOMENT</span><h3>{!online&&!cached?'Nothing saved. Yet.':'The Web can wait for you.'}</h3><p>{!online&&!cached?'Reconnect and save this article before you leave the network.':'A thoughtful article, available even when the connection disappears.'}</p></article><div className="demo-actions"><button className="small-button" disabled={!online||cached} onClick={()=>setCached(true)}>{cached?<Check size={16}/>:<Plus size={16}/>} {cached?'Article cached':'Save for offline'}</button><button className="small-button" onClick={()=>setLoaded(true)}><ArrowClockwise size={16}/>Request article</button></div><p role="status" className="result-message">{loaded?(online?'Served from the network.':cached?'Served from the cache. No connection needed.':'No network, and no cached response.'):'Save the article, disconnect, then request it again.'}</p></div></Window><Note>The controls simulate a cache strategy. They do not change your connection or install a service worker.</Note></div>}

const wasmBytes=new Uint8Array([0,97,115,109,1,0,0,0,1,7,1,96,2,127,127,1,127,3,2,1,0,7,7,1,3,97,100,100,0,0,10,9,1,7,0,32,0,32,1,106,11]);
export function WasmDemo(){const[a,setA]=useState(19),[b,setB]=useState(23),[result,setResult]=useState(null),[error,setError]=useState('');async function run(){try{const {instance}=await WebAssembly.instantiate(wasmBytes);setResult(instance.exports.add(a,b));setError('')}catch{setError('WebAssembly is unavailable in this browser.')}}return <div className="demo"><div className="demo-topline"><span>11 / THE PORTABLE PROGRAM</span><span>Real WebAssembly execution</span></div><Window name="a-small-program.wasm"><CodeBlock>{'(module\n  (func (export "add")\n    (param $a i32) (param $b i32) (result i32)\n    local.get $a\n    local.get $b\n    i32.add))'}</CodeBlock><div className="wasm-math"><label><span>INPUT A</span><input type="number" aria-label="WebAssembly input A" min="-999" max="999" value={a} onChange={e=>{setA(Math.max(-999,Math.min(999,Math.trunc(+e.target.value))));setResult(null)}}/></label><Plus size={26}/><label><span>INPUT B</span><input type="number" aria-label="WebAssembly input B" min="-999" max="999" value={b} onChange={e=>{setB(Math.max(-999,Math.min(999,Math.trunc(+e.target.value))));setResult(null)}}/></label><span className="equals">=</span><output aria-live="polite">{result===null?'?':result}</output></div><div className="wasm-actions"><button className="pill-primary" onClick={run}><Play size={18}/>Run the Wasm module</button><span role="status">{error||(result===null?'A 41-byte program, ready to run.':'Computed by WebAssembly in your browser.')}</span></div></Window><Note>The code above is WebAssembly text format. Its pre-encoded binary is instantiated and called when you press Run. This is a real calculation, not a benchmark.</Note></div>}

export function GpuDemo(){const[mode,setMode]=useState('parallel'),[playing,setPlaying]=useState(false),[density,setDensity]=useState(40),[result,setResult]=useState(''),[busy,setBusy]=useState(false);
 async function compute(){setBusy(true);let device;try{if(!navigator.gpu)throw new Error('unavailable');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw new Error('unavailable');device=await adapter.requestDevice();const input=new Float32Array([1,2,3,4]);const b=device.createBuffer({size:16,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC});device.queue.writeBuffer(b,0,input);const out=device.createBuffer({size:16,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const mod=device.createShaderModule({code:'@group(0) @binding(0) var<storage,read_write> values: array<f32>; @compute @workgroup_size(4) fn main(@builtin(global_invocation_id) id: vec3<u32>) { values[id.x] = values[id.x] * values[id.x]; }'});const pipeline=device.createComputePipeline({layout:'auto',compute:{module:mod,entryPoint:'main'}});const group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:b}}]});const encoder=device.createCommandEncoder();const pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.dispatchWorkgroups(1);pass.end();encoder.copyBufferToBuffer(b,0,out,0,16);device.queue.submit([encoder.finish()]);await out.mapAsync(GPUMapMode.READ);const values=Array.from(new Float32Array(out.getMappedRange().slice(0)));out.unmap();b.destroy();out.destroy();setResult(`Actual GPU result: [${values.join(', ')}]. Four inputs squared in a compute shader.`)}catch{setResult('WebGPU is unavailable in this browser or context. The illustration above still works; no GPU calculation was performed.')}finally{device?.destroy();setBusy(false)}}
 return <div className="demo"><div className="demo-topline"><span>12 / THE PARALLEL IDEA</span><output>{density*density} points</output></div><Tabs label="Computation illustration" items={[["sequential","One row at a time"],["parallel","Many together"]]} value={mode} onChange={setMode}/><div className="gpu-surface"><WaveField parallel={mode==='parallel'} playing={playing} density={density} label="An illustrative point surface comparing sequential and parallel updates"/></div><div className="demo-actions"><button className="small-button" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Animate'}</button><label className="range-label density"><span>Density</span><input aria-label="Point density" type="range" min="20" max="60" value={density} onChange={e=>setDensity(+e.target.value)}/></label></div><button className="text-link demo-cta" disabled={busy} onClick={compute}>{busy?'Requesting a GPU…':'Try a real WebGPU calculation'}<ArrowRight size={18}/></button>{result&&<p role="status" className="gpu-result">{result}</p>}<Note>The surface is a Canvas 2D illustration, not a speed test. The optional calculation uses WebGPU if your browser and device support it.</Note></div>
}

export const demos={html:HtmlDemo,server:CookieDemo,css:CssDemo,javascript:JsDemo,dom:DomDemo,ajax:AjaxDemo,v8:RuntimeDemo,responsive:ResponsiveDemo,platform:PlatformDemo,offline:OfflineDemo,wasm:WasmDemo,webgpu:GpuDemo};
