import React,{useState} from 'react';
import {ArrowRight,ArrowClockwise,CursorClick,WifiHigh,WifiSlash,Globe,Plus,Check} from '@phosphor-icons/react';
const captions={html:['Toggle the link','Links make documents navigable.'],server:['Reverse the journey','A request can run a program and return a response.'],css:['Change the style','Presentation changes. The document stays.'],javascript:['Click the button','A click becomes a little program.'],dom:['Toggle the highlight','An element in the tree is an element on the page.'],ajax:['Switch the updated tile','Only the requested part needs to change.'],v8:['Change the scheduling','Other work can continue while I/O waits.'],responsive:['Change the screen width','One layout responds to the space available.'],platform:['Change the perspective','A flat page gains a spatial canvas.'],offline:['Toggle the connection','A web experience can live beyond its browser tab.'],wasm:['Toggle the module result','A portable module returns a result to the page.'],webgpu:['Regroup the tasks','Independent tasks can move together.']};
function MiniBrowser({children,className=''}){return <div className={'era-browser '+className}><div className="era-browser-bar"><i/><i/><i/><span>the evolving web</span></div>{children}</div>}
export function EraScene({id}){
 const [manual,setManual]=useState(null),[clicks,setClicks]=useState(1);
 const activate=e=>{const visible=parseFloat(getComputedStyle(e.currentTarget.closest('.era-scene')).getPropertyValue('--scene-progress'))||0;setManual(v=>id==='javascript'?1:(v??visible)>=.5?0:1);setClicks(v=>v+1)};
 let scene;
 switch(id){
 case 'html':scene=<div className="link-scene"><div className="era-document"><span>HTML / a document</span><b>A connected idea.</b><code>&lt;a href="/next"&gt;</code><u>Follow this thought</u><i/><i/></div><svg viewBox="0 0 320 220" aria-hidden="true"><path className="era-drawn-link" d="M110 127C170 127 150 57 223 66" pathLength="1"/><circle className="era-arrival" cx="223" cy="66" r="4"/></svg><div className="era-document linked-document"><span>/next</span><b>Another idea.</b><i/><i/><i/></div></div>;break;
 case 'server':scene=<div className="request-scene"><div className="era-computer"><Globe size={37} weight="thin"/><span>Browser</span></div><div className="era-server"><i/><i/><i/><span>Server program</span></div><span className="era-request">GET /ideas</span><span className="era-response">200 OK · Set-Cookie</span><div className="era-cookie">session = 01 <Check size={12}/></div><svg viewBox="0 0 320 220" aria-hidden="true"><path d="M80 83H243M243 129H80"/></svg></div>;break;
 case 'css':scene=<MiniBrowser className="css-scene"><div className="style-specimen"><small>The daily web</small><strong>Same words.<br/>New expression.</strong><p>Ideas belong together.</p></div><code>color: blue; font-size: 2rem;</code></MiniBrowser>;break;
 case 'javascript':scene=<MiniBrowser className="js-scene"><code>button.onclick = () =&gt; ++likes</code><div className="era-click-button"><CursorClick size={23}/><span>Like this idea</span></div><div className="era-counter"><span className="era-before">0</span><span className="era-after">{Math.max(1,clicks)}</span><small>likes</small></div><span className="era-pointer">↖</span></MiniBrowser>;break;
 case 'dom':scene=<div className="dom-scene"><svg viewBox="0 0 320 220" aria-hidden="true"><path d="M90 47V74M90 74H37V100M90 74H146V100M146 130V157"/><rect x="62" y="24" width="56" height="27" rx="7"/><text x="90" y="42">article</text><rect x="12" y="99" width="50" height="29" rx="7"/><text x="37" y="118">h1</text><rect className="era-node-active" x="122" y="99" width="50" height="29" rx="7"/><text x="147" y="118">p</text><rect x="121" y="155" width="52" height="28" rx="7"/><text x="147" y="174">text</text><path className="era-drawn-link" d="M172 113C211 113 191 108 225 108" pathLength="1"/></svg><div className="era-dom-page"><b>A live page</b><p className="era-node-active">A thought.</p><i/><i/></div></div>;break;
 case 'ajax':scene=<MiniBrowser className="ajax-scene"><span className="era-inbox-label">INBOX / your place is kept</span><div className="era-inbox"><div><i/><span>A conversation</span></div><div className="era-live-tile"><i/><span className="era-before">Waiting for news…</span><span className="era-after">A new idea arrived.</span></div><div><i/><span>Your unfinished draft</span></div></div><span className="era-data-packet">JSON →</span></MiniBrowser>;break;
 case 'v8':scene=<div className="runtime-scene"><div className="era-chip">V8<small>JavaScript engine</small></div><div className="era-runtime-lanes"><p><span>File I/O</span><i className="era-wait-track"><b/></i></p><p><span>Next visitor</span><i className="era-work-track"><b/></i></p><code>While we wait, keep working.</code></div></div>;break;
 case 'responsive':scene=<div className="responsive-scene"><MiniBrowser><div className="era-fluid-page"><b>One Web.</b><div><i/><i/><i/></div></div></MiniBrowser><span className="era-width-line">← &nbsp; available space &nbsp; →</span></div>;break;
 case 'platform':scene=<div className="platform-scene"><svg viewBox="0 0 320 220" aria-hidden="true" className="era-wireframe">{Array.from({length:12},(_,i)=><path key={i} d={`M${30+i*10} ${125+i*3} Q${120+i*8} ${22+i*5} ${185+i*9} ${85+i*4}`}/>)}{Array.from({length:12},(_,i)=><path key={'b'+i} d={`M${30+i*14} ${125-i*4} Q${130+i*7} ${170-i*12} ${140+i*13} ${158-i*3}`}/>)}</svg><span className="era-axis axis-x">x</span><span className="era-axis axis-y">y</span><span className="era-axis axis-z">z</span><code>canvas + GPU graphics</code></div>;break;
 case 'offline':scene=<div className="pwa-scene"><div className="era-phone"><div className="era-phone-notch"/><div className="era-app-icon"><Globe size={26}/></div><b>The daily web</b><small>One URL. An app-like home.</small><div className="era-saved"><Check size={13}/> Article saved</div></div><div className="era-network-state"><span className="era-before"><WifiHigh size={23}/> Online</span><span className="era-after"><WifiSlash size={23}/> Still available</span></div><code>manifest + service worker</code></div>;break;
 case 'wasm':scene=<div className="wasm-scene"><div className="era-source-code"><span>C / C++ / Rust</span><code>add(9, 4)</code><i/><i/></div><span className="era-compile-arrow">→</span><div className="era-wasm-module"><b>Wasm</b><code>00 61 73 6d</code></div><div className="era-wasm-result"><small>back in the page</small><strong>13</strong></div></div>;break;
 case 'webgpu':scene=<div className="gpu-scene"><div className="era-task-grid">{Array.from({length:48},(_,i)=><i key={i} style={{'--task':i,'--lane':i%8}}/>)}</div><div className="era-task-caption"><span>48 independent tasks</span><span>One operation × many inputs</span></div></div>;break;
 }
 return <div className={'era-scene scene-'+id} style={manual===null?undefined:{'--scene-progress':manual}}><div className="era-scene-art" role="img" aria-label={captions[id][1]}>{scene}</div><div className="era-scene-controls"><button className="scene-action" onClick={activate} aria-label={captions[id][0]}>{manual===1?<ArrowClockwise size={14}/>:id==='javascript'?<Plus size={14}/>:<ArrowRight size={14}/>}<span>{captions[id][0]}</span></button><small>Scroll or try it</small></div></div>
}
